name: CastleFight
version: '0.1.1'
main: ru.rstudios.castlefight.CastleFight
api-version: '1.20'
commands:
  gamemode:
    usage: /gamemode <0/1/2/3> (player)
    description: "Изменение режима игры"
    permission: castlefight.gamemode
    aliases:
      - gm
      - gmode
  stats:
    usage: /stats <money/rating>
    description: none

  spawn:
    usage: /spawn <roleName> <towerName> <towerLevel>
    description: Создаёт сущность заданной башни и заданного уровня
    permission: castlefight.spawn

  structure:
    usage: /structure <save|load> <roleName> <towerName> <towerLevel>
    description: Загружает здание роли если такое имеется
    permission: castlefight.structure

  openmenu:
    usage: /openmenu <player> <menuName>
    description: Открывает указанное меню игроку
    permission: castlefight.openmenu

  creategame:
    usage: /creategame <playersCount>
    description: Создаёт игровой мир и переносит туда игрока
    permission: castlefight.creategame

  closegame:
    usage: /closegame <ID> <playersPlanned>
    description: Закрывает игру с указанным ID
    permission: castlefight.closegame

  world:
    usage: /world <worldName>
    description: Телепортирует исполнителя в указанный мир
    permission: castlefight.world