name: CastleFight
version: '0.1.1'
main: ru.rstudios.castlefight.CastleFight
api-version: '1.20'
commands:
  gamemode:
    usage: /gamemode <0/1/2/3> (player)
    description: "Изменение режима игры"
    permission: castlefight.gamemode
    aliases:
      - gm
      - gmode
  stats:
    usage: /stats <money/rating>
    description: none